In [26]:
import pandas as pd

In [27]:
data = pd.read_csv("datasets_modif.csv")
data

,Unnamed: 0,start_date,end_date,created_on,lat,lon,l3,l4,rooms,surface_total,surface_covered,price,price_period,title,description,property_type
0,137,2020-08-22,2020-09-04,2020-08-22,-34.638910,-58.476073,Floresta,Sin datos,NaN,372.0,NaN,450000.0,Mensual,Exclente lote !!,"Lote 365 mts 8,90 x 43 mts C3 II.. FOT 3.6 PAR...",Lote
1,149,2020-08-22,2020-09-04,2020-08-22,-34.562124,-58.464449,Belgrano,Sin datos,NaN,NaN,NaN,20000.0,Mensual,Excelente cochera fija y cubierta en edificio ...,"Muy buena cochera, en el 4to piso en excelente...",Cochera
2,153,2020-08-22,2020-09-04,2020-08-22,-34.598112,-58.400784,Recoleta,Sin datos,NaN,265.0,265.0,600000.0,Mensual,Oficina comercial · 265m² · 2 Cochera,Gran Oportunidad! Unica piso de oficinas de 26...,Oficina
3,154,2020-08-22,2020-09-04,2020-08-22,-34.614123,-58.378985,Monserrat,Sin datos,5.0,150.0,150.0,195000.0,Mensual,Importante Oficina en Micro centro de 150 m2.,Importante Oficina de de 150 m2 con palier pr...,Oficina
4,155,2020-08-22,2020-09-04,2020-08-22,-34.603233,-58.385218,San Nicolás,Sin datos,1.0,NaN,12.0,22000.0,Mensual,Oficina - San Nicolas,VENTA DE OFICINA A METROS DEL PALACIO DE TRIBU...,Oficina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179801,999940,2020-12-04,2021-01-10,2020-12-04,-34.613926,-58.499472,Monte Castro,Sin datos,6.0,243.0,180.0,250000.0,NaN,PH 6 Ambientes c/cochera y terraza en Monte Ca...,Corredor Responsable: Rene Vera - CUCICBA 6778...,PH
179802,999959,2020-12-04,9999-12-31,2020-12-04,-34.570592,-58.462513,Belgrano,Sin datos,9.0,641.0,461.0,1650000.0,Mensual,Casa impecable en venta en la mejor zona de -...,Casa en pleno Belgrano R reciclada con excelen...,Casa
179803,999977,2020-12-04,2020-12-30,2020-12-04,-34.573074,-58.419353,Palermo,Sin datos,8.0,419.0,375.0,1350000.0,Mensual,Impactante vista a los parques. 420 m2 con coc...,Piso de 419 m2 en un emblemático edificio mode...,Departamento
179804,999978,2020-12-04,9999-12-31,2020-12-04,-34.563411,-58.445656,Belgrano,Sin datos,6.0,285.0,270.0,1400000.0,Mensual,Departamento - Belgrano,"Piso de 285mts, en la mejor zona de Belgrano.<...",Departamento
179805,999997,2020-12-04,9999-12-31,2020-12-04,-34.576445,-58.432603,Palermo,Sin datos,14.0,615.0,425.0,570000.0,Mensual,Edificio Comercial en excelente zona de Paler...,Edificio Comercial CON ENTRADA INDEPENDIENTE S...,Local comercial

In [28]:
drop_tablas = ["title", "description", "price_period", "Unnamed: 0", "start_date", "end_date", "created_on"]
data.drop(columns = drop_tablas, inplace = True)

In [29]:
dict_renombrar= {"l3":"Barrio", "l4":"Zona", "rooms":"Habitaciones", "price":"Precio", "property_type":"Tipo_propiedad"}
data.rename(columns=dict_renombrar, inplace =True)

In [30]:
data

,lat,lon,Barrio,Zona,Habitaciones,surface_total,surface_covered,Precio,Tipo_propiedad
0,-34.638910,-58.476073,Floresta,Sin datos,NaN,372.0,NaN,450000.0,Lote
1,-34.562124,-58.464449,Belgrano,Sin datos,NaN,NaN,NaN,20000.0,Cochera
2,-34.598112,-58.400784,Recoleta,Sin datos,NaN,265.0,265.0,600000.0,Oficina
3,-34.614123,-58.378985,Monserrat,Sin datos,5.0,150.0,150.0,195000.0,Oficina
4,-34.603233,-58.385218,San Nicolás,Sin datos,1.0,NaN,12.0,22000.0,Oficina
...,...,...,...,...,...,...,...,...,...
179801,-34.613926,-58.499472,Monte Castro,Sin datos,6.0,243.0,180.0,250000.0,PH
179802,-34.570592,-58.462513,Belgrano,Sin datos,9.0,641.0,461.0,1650000.0,Casa
179803,-34.573074,-58.419353,Palermo,Sin datos,8.0,419.0,375.0,1350000.0,Departamento
179804,-34.563411,-58.445656,Belgrano,Sin datos,6.0,285.0,270.0,1400000.0,Departamento
179805,-34.576445,-58.432603,Palermo,Sin datos,14.0,615.0,425.0,570000.0,Local comercial

In [31]:
data = pd.get_dummies(data,  drop_first=True)
data

,lat,lon,Habitaciones,surface_total,surface_covered,Precio,Barrio_Agronomía,Barrio_Almagro,Barrio_Balvanera,Barrio_Barracas,...,Zona_Sin datos,Tipo_propiedad_Casa de campo,Tipo_propiedad_Cochera,Tipo_propiedad_Departamento,Tipo_propiedad_Depósito,Tipo_propiedad_Local comercial,Tipo_propiedad_Lote,Tipo_propiedad_Oficina,Tipo_propiedad_Otro,Tipo_propiedad_PH
0,-34.638910,-58.476073,NaN,372.0,NaN,450000.0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1,-34.562124,-58.464449,NaN,NaN,NaN,20000.0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
2,-34.598112,-58.400784,NaN,265.0,265.0,600000.0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
3,-34.614123,-58.378985,5.0,150.0,150.0,195000.0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
4,-34.603233,-58.385218,1.0,NaN,12.0,22000.0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179801,-34.613926,-58.499472,6.0,243.0,180.0,250000.0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
179802,-34.570592,-58.462513,9.0,641.0,461.0,1650000.0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
179803,-34.573074,-58.419353,8.0,419.0,375.0,1350000.0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
179804,-34.563411,-58.445656,6.0,285.0,270.0,1400000.0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
179805,-34.576445,-58.432603,14.0,615.0,425.0,570000.0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0

In [32]:
data["Habitaciones"].loc[data["Habitaciones"].isnull()] = "Sin datos"

C:\Users\Ionatan\AppData\Local\Temp\ipykernel_7016\1858713240.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Habitaciones"].loc[data["Habitaciones"].isnull()] = "Sin datos"

In [33]:
#data = pd.get_dummies(data,  drop_first=True)
data

,lat,lon,Habitaciones,surface_total,surface_covered,Precio,Barrio_Agronomía,Barrio_Almagro,Barrio_Balvanera,Barrio_Barracas,...,Zona_Sin datos,Tipo_propiedad_Casa de campo,Tipo_propiedad_Cochera,Tipo_propiedad_Departamento,Tipo_propiedad_Depósito,Tipo_propiedad_Local comercial,Tipo_propiedad_Lote,Tipo_propiedad_Oficina,Tipo_propiedad_Otro,Tipo_propiedad_PH
0,-34.638910,-58.476073,Sin datos,372.0,NaN,450000.0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1,-34.562124,-58.464449,Sin datos,NaN,NaN,20000.0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
2,-34.598112,-58.400784,Sin datos,265.0,265.0,600000.0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
3,-34.614123,-58.378985,5.0,150.0,150.0,195000.0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
4,-34.603233,-58.385218,1.0,NaN,12.0,22000.0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179801,-34.613926,-58.499472,6.0,243.0,180.0,250000.0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
179802,-34.570592,-58.462513,9.0,641.0,461.0,1650000.0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
179803,-34.573074,-58.419353,8.0,419.0,375.0,1350000.0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
179804,-34.563411,-58.445656,6.0,285.0,270.0,1400000.0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
179805,-34.576445,-58.432603,14.0,615.0,425.0,570000.0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0

In [34]:
import numpy as np
dict_amb = {'Sin datos':'Sin datos',1:'monoambiente',2:'dos amb',3:'3 amb'}

In [35]:
data['Habitaciones'] = data['Habitaciones'].map(dict_amb).fillna('4+ amb')

In [36]:
data

,lat,lon,Habitaciones,surface_total,surface_covered,Precio,Barrio_Agronomía,Barrio_Almagro,Barrio_Balvanera,Barrio_Barracas,...,Zona_Sin datos,Tipo_propiedad_Casa de campo,Tipo_propiedad_Cochera,Tipo_propiedad_Departamento,Tipo_propiedad_Depósito,Tipo_propiedad_Local comercial,Tipo_propiedad_Lote,Tipo_propiedad_Oficina,Tipo_propiedad_Otro,Tipo_propiedad_PH
0,-34.638910,-58.476073,Sin datos,372.0,NaN,450000.0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1,-34.562124,-58.464449,Sin datos,NaN,NaN,20000.0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
2,-34.598112,-58.400784,Sin datos,265.0,265.0,600000.0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
3,-34.614123,-58.378985,4+ amb,150.0,150.0,195000.0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
4,-34.603233,-58.385218,monoambiente,NaN,12.0,22000.0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179801,-34.613926,-58.499472,4+ amb,243.0,180.0,250000.0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
179802,-34.570592,-58.462513,4+ amb,641.0,461.0,1650000.0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
179803,-34.573074,-58.419353,4+ amb,419.0,375.0,1350000.0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
179804,-34.563411,-58.445656,4+ amb,285.0,270.0,1400000.0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
179805,-34.576445,-58.432603,4+ amb,615.0,425.0,570000.0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0

In [37]:
data = pd.get_dummies(data,  drop_first=True)
data

,lat,lon,surface_total,surface_covered,Precio,Barrio_Agronomía,Barrio_Almagro,Barrio_Balvanera,Barrio_Barracas,Barrio_Barrio Norte,...,Tipo_propiedad_Depósito,Tipo_propiedad_Local comercial,Tipo_propiedad_Lote,Tipo_propiedad_Oficina,Tipo_propiedad_Otro,Tipo_propiedad_PH,Habitaciones_4+ amb,Habitaciones_Sin datos,Habitaciones_dos amb,Habitaciones_monoambiente
0,-34.638910,-58.476073,372.0,NaN,450000.0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
1,-34.562124,-58.464449,NaN,NaN,20000.0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,-34.598112,-58.400784,265.0,265.0,600000.0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
3,-34.614123,-58.378985,150.0,150.0,195000.0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
4,-34.603233,-58.385218,NaN,12.0,22000.0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179801,-34.613926,-58.499472,243.0,180.0,250000.0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
179802,-34.570592,-58.462513,641.0,461.0,1650000.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
179803,-34.573074,-58.419353,419.0,375.0,1350000.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
179804,-34.563411,-58.445656,285.0,270.0,1400000.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
179805,-34.576445,-58.432603,615.0,425.0,570000.0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0

In [38]:
data_limpia = data.dropna()
data_limpia

,lat,lon,surface_total,surface_covered,Precio,Barrio_Agronomía,Barrio_Almagro,Barrio_Balvanera,Barrio_Barracas,Barrio_Barrio Norte,...,Tipo_propiedad_Depósito,Tipo_propiedad_Local comercial,Tipo_propiedad_Lote,Tipo_propiedad_Oficina,Tipo_propiedad_Otro,Tipo_propiedad_PH,Habitaciones_4+ amb,Habitaciones_Sin datos,Habitaciones_dos amb,Habitaciones_monoambiente
2,-34.598112,-58.400784,265.0,265.0,600000.0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
3,-34.614123,-58.378985,150.0,150.0,195000.0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
8,-34.599676,-58.371434,80.0,80.0,155000.0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
9,-34.599676,-58.371434,160.0,160.0,310000.0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
11,-34.600004,-58.417191,38.0,31.0,110000.0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179801,-34.613926,-58.499472,243.0,180.0,250000.0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
179802,-34.570592,-58.462513,641.0,461.0,1650000.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
179803,-34.573074,-58.419353,419.0,375.0,1350000.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
179804,-34.563411,-58.445656,285.0,270.0,1400000.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
179805,-34.576445,-58.432603,615.0,425.0,570000.0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0

In [39]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

In [40]:
X = data_limpia.drop(columns = 'Precio')   #variables predictora
y = data_limpia["Precio"]   #variable a predecir

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=138)

In [42]:
arbol = DecisionTreeRegressor()

In [43]:
arbol.fit(X_train, y_train)

DecisionTreeRegressor()

In [44]:
y_pred_train = arbol.predict(X_train)
mse_train_arbol = mean_squared_error(y_train, y_pred_train, squared = False)
mse_train_arbol

16037.149377586393

In [45]:
y_pred_test = arbol.predict(X_test)
mse_test_arbol = mean_squared_error(y_test, y_pred_test, squared = False)
mse_test_arbol

282398.1103460275

In [47]:
arbol = DecisionTreeRegressor(max_depth = 10)
arbol.fit(X_train, y_train)
y_pred_train = arbol.predict(X_train)
mse_train_arbol = mean_squared_error(y_train, y_pred_train, squared = False)
print (mse_train_arbol)
y_pred_test = arbol.predict(X_test)
mse_test_arbol = mean_squared_error(y_test, y_pred_test, squared = False)
print (mse_test_arbol)

173933.3342254706
265639.36849695223

In [56]:
from sklearn.model_selection import GridSearchCV

dict_hiper = {'max_depth': [None,1,2,3,4,5,6,7,8,9,10,15,20],'min_samples_split':[2,100,1000]}

model = GridSearchCV(estimator = arbol, param_grid = dict_hiper, cv=5)
model.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(max_depth=10),
             param_grid={'max_depth': [None, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15,
                                       20],
                         'min_samples_split': [2, 100, 1000]})

In [58]:
model.best_estimator_
model.best_params_

{'max_depth': 7, 'min_samples_split': 2}

In [ ]:
pd.DataFrame(model.cv_results_)

In [72]:
from sklearn.ensemble import RandomForestClassifier

In [73]:
random_forest = RandomForestClassifier()

In [74]:
random_forest.fit(X_train, y_train)

MemoryError: could not allocate 5272240128 bytes

In [ ]:
y_pred_train_rf = random_forest.predict(X_train)

In [ ]:
exactitud_train_rf = accuracy_score(y_train, y_pred_train_rf)
exactitud_train_rf

In [ ]:
y_pred_rf = random_forest.predict(X_test)